### ISSUE TITLE
Multiple issues with View.java

### ISSUE THREAD

**Issue by dustedrob** [crashlytics/digits-android#12]
I'm using version 1.5.1 and this has become a very annoying an consistent problem. My crashlytics log is full of crashes like this:

```
View.java line 16540
android.view.View.measure


java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to com.android.internal.widget.ActionBarOverlayLayout$LayoutParams
   at com.android.internal.widget.ActionBarOverlayLayout.applyInsets(ActionBarOverlayLayout.java:172)
   at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:317)
   at android.view.View.measure(View.java:16540)
   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5137)
   at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
   at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
   at android.view.View.measure(View.java:16540)
   at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1942)
   at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1132)
   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1321)
   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1019)
   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5725)
   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
   at android.view.Choreographer.doCallbacks(Choreographer.java:574)
   at android.view.Choreographer.doFrame(Choreographer.java:544)
   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
   at android.os.Handler.handleCallback(Handler.java:733)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:136)
   at android.app.ActivityThread.main(ActivityThread.java:5086)
   at java.lang.reflect.Method.invokeNative(Method.java)
   at java.lang.reflect.Method.invoke(Method.java:515)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
   at dalvik.system.NativeStart.main(NativeStart.java)
```

The specific line is never the same and it only happens during the Digits authentication portion of my app. I have never been able to reproduce it and i'm not even sure if it causes a crash on the app but my Crashlytic log is always full of this issues. Any idea of what might be causing it?

**Comment by efrohnhoefer** [comment]
Hi @dustedrob, Thank you for reporting this issue. My gut feeling is that there is an issue with the AppCompat Library. What version of the AppCompat library are you using? Do you know where is the auth process this crash happens?

**Comment by dustedrob** [comment]
Everything between 21.0.x and 22 has issues. I don't really know where in the auth process it happens as i have never been able to reproduce it myself.

**Comment by efrohnhoefer** [comment]
Can you email support@fabric.io with a link to your crash?

**Comment by dustedrob** [comment]
Will do.
