### ISSUE TITLE
Could not verify some numbers: retrofit.RetrofitError: No authentication challenges found

### ISSUE THREAD

**Issue by ahmedgalal** [crashlytics/digits-android#69]
Using digits 1.11.1 on Android 4.1

Run the sample app, try to verify the following number: +20 1271111003 (Egypt/Orange operator)
You will get the UI error message "please check your network and try again"

Investigating further, looking at the code the LoginOrSignupComposer is getting a failure with the following exception

`com.example.app.digits E/Digits: HTTP Error: No authentication challenges found
                                                              com.twitter.sdk.android.core.TwitterApiException: No authentication challenges found
                                                                  at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:390)
                                                                  at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
                                                                  at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
                                                                  at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
                                                                  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
                                                                  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                                                  at java.lang.Thread.run(Thread.java:856)
`

Searching about the issue online it is possible that it happens because of different implementations of "UrlConnection" on Android versions.
[http://stackoverflow.com/questions/17121213/java-io-ioexception-no-authentication-challenges-found](url)

But i don't understand how can i verify some other numbers with no problems on the same version, same country and same operator like (+20 1227070111).

Am not sure if upgrading to the latest retrofit would fix this problem, is this a known bug, is there any workarounds ?

Best

**Comment by ahmedgalal** [comment]
i still don't understand why some numbers would verify and some numbers wouldn't on the same device and same android version, however here is a solution.

adding the dependency okhttp-url-connection 2.7.1 would fix that issue, along side with okhttp3-url-connection 3.3.1

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
