### ISSUE TITLE
Sign in with Digits failure - For some numbers

### ISSUE THREAD

**Issue by m4mum** [crashlytics/digits-android#70]
Hi

Trying to OTP verify few numbers, it fails from all different device/same app version. Other numbers are able to get verify easily from same device/app version.

If you want particular number for which It is getting failed, pls mail me on Raxit@m4mum.com as don't want to give that number in public.

sharingo D/Digits: Sign in with Digits failure
com.digits.sdk.android.DigitsException: Try Again
 at com.digits.sdk.android.LoginResultReceiver.onReceiveResult(LoginResultReceiver.java:55)
 at android.os.ResultReceiver$MyResultReceiver.send(ResultReceiver.java:59)
 at android.os.ResultReceiver.send(ResultReceiver.java:93)
 at com.digits.sdk.android.FailureControllerImpl.sendFailure(FailureControllerImpl.java:50)
 at com.digits.sdk.android.FailureActivityDelegateImpl$1.onClick(FailureActivityDelegateImpl.java:80)
 at android.view.View.performClick(View.java:4802)
 at android.view.View$PerformClick.run(View.java:20101)
 at android.os.Handler.handleCallback(Handler.java:810)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:189)
 at android.app.ActivityThread.main(ActivityThread.java:5532)
 at java.lang.reflect.Method.invoke(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:372)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
07-04 19:56:14.268 12017-12017/com.smartmumbaikar.sharingo D/AndroidRuntime: Shutting down VM

**Comment by jaydeepw** [comment]
Numbers starting with 91

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
