### ISSUE TITLE
Exception (crash) with API level 19. KitKat 4.4.2 

### ISSUE THREAD

**Issue by samshm** [crashlytics/digits-android#74]
Hi,

Dependencies:
    // digits
    compile('com.digits.sdk.android:digits:1.11.1@aar') {
        transitive = true;
    }
    // digits To support older Android devices running versions of Android lower than 5.0
    compile 'com.squareup.okhttp:okhttp:2.7.3'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.7.3'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    //
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.4.1'

Exception (about Retrofit):
`java.lang.NoClassDefFoundError: retrofit.RestMethodInfo$RequestType
                                                                        at retrofit.RestMethodInfo.<init>(RestMethodInfo.java:82)
                                                                        at retrofit.RestAdapter.getMethodInfo(RestAdapter.java:213)
                                                                        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:236)
                                                                        at com.twitter.sdk.android.core.internal.oauth.$Proxy2.getAppAuthToken(Native Method)
                                                                        at com.twitter.sdk.android.core.internal.oauth.OAuth2Service.requestAppAuthToken(OAuth2Service.java:113)
                                                                        at com.twitter.sdk.android.core.internal.oauth.OAuth2Service.requestGuestAuthToken(OAuth2Service.java:104)
                                                                        at com.digits.sdk.android.DigitsGuestSessionProvider.requestAuth(DigitsGuestSessionProvider.java:53)
                                                                        at com.twitter.sdk.android.core.internal.AuthRequestQueue.requestAuth(AuthRequestQueue.java:100)
                                                                        at com.twitter.sdk.android.core.internal.AuthRequestQueue.addRequest(AuthRequestQueue.java:73)
                                                                        at com.digits.sdk.android.DigitsAuthRequestQueue.addClientRequest(DigitsAuthRequestQueue.java:42)
                                                                        at com.digits.sdk.android.DigitsClient.authDevice(DigitsClient.java:169)
                                                                        at com.digits.sdk.android.LoginOrSignupComposer.beginLogin(LoginOrSignupComposer.java:131)
                                                                        at com.digits.sdk.android.LoginOrSignupComposer.start(LoginOrSignupComposer.java:123)
                                                                        at com.digits.sdk.android.PhoneNumberController.executeRequest(PhoneNumberController.java:136)
                                                                        at com.digits.sdk.android.DigitsActivityDelegateImpl$1.onClick(DigitsActivityDelegateImpl.java:44)
                                                                        at android.view.View.performClick(View.java:4442)
                                                                        at android.view.View$PerformClick.run(View.java:18473)
                                                                        at android.os.Handler.handleCallback(Handler.java:733)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5105)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
                                                                        at dalvik.system.NativeStart.main(Native Method)`

**Comment by vishal901** [comment]
compile('com.twitter.sdk.android:twitter:2.3.1@aar') {
        transitive = true;
    }

add this with retrofit solve this error
