### ISSUE TITLE
ArrayIndexOutOfBounds Exception at BucketedTextChangeListener 

### ISSUE THREAD

**Issue by vivekkartha** [crashlytics/digits-android#82]
I have pasted the crash log below :

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=7; index=-5
       at com.digits.sdk.android.BucketedTextChangeListener.onTextChanged(BucketedTextChangeListener.java:58)
       at android.widget.TextView.sendOnTextChanged(TextView.java:8041)
       at android.widget.TextView.handleTextChanged(TextView.java:8104)
       at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:9970)
       at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:982)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:528)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:465)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:38)
       at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:709)
       at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:211)
       at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:191)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:286)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5673)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:969)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
```

**Comment by bikranttripathi** [comment]
I'm getting this crash as well on **HTC Desire D530** running **Android 6.0.1**.

The exception looks like this on my end.
`
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=7; index=-2
       at com.digits.sdk.android.BucketedTextChangeListener.onTextChanged(BucketedTextChangeListener.java:58)
       at android.widget.TextView.sendOnTextChanged(TextView.java:8003)
       at android.widget.TextView.handleTextChanged(TextView.java:8065)
       at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:10169)
       at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1045)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:571)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:492)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:34)
       at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:685)
       at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:445)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:340)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:168)
       at android.app.ActivityThread.main(ActivityThread.java:5885)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
`

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
