### ISSUE TITLE
NullPointerException  getAuthClient()

### ISSUE THREAD

**Issue by goraga1** [crashlytics/digits-android#98]
```
 java.lang.NullPointerException: Attempt to invoke virtual method 'com.digits.sdk.android.AuthClient com.digits.sdk.android.Digits.getAuthClient()' on a null object reference
                                                                   at com.digits.sdk.android.DigitsAuthButton.getAuthClient(DigitsAuthButton.java:104)
                                                                   at com.digits.sdk.android.DigitsAuthButton.onClick(DigitsAuthButton.java:73)
                                                                   at android.view.View.performClick(View.java:5669)
                                                                   at android.view.View$PerformClick.run(View.java:22539)
                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6290)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
```
        TwitterAuthConfig authConfig = new TwitterAuthConfig(TWITTER_KEY, TWITTER_SECRET);
        Fabric.with(getActivity(), new Crashlytics(), new TwitterCore(authConfig), new Digits.Builder().build());


        authCallback = new AuthCallback() {
            @Override
            public void success(DigitsSession session, String phoneNumber) {
                numberVerified(phoneNumber);
            }

            @Override
            public void failure(DigitsException exception) {
                // Do something on failure
            }
        };

        DigitsAuthButton authButton = (DigitsAuthButton) view.findViewById(R.id.auth_button);
        authButton.setCallback(authCallback);

        authButton.setText(getString(R.string.send_confirmation_code));
        authButton.setBackgroundColor(ContextCompat.getColor(getContext(), R.color.colorAccent));
      authButton.setAuthTheme(R.style.CustomDigitsTheme);
        authButton.performClick();

```

**Comment by goraga1** [comment]
if line 104 was deleting there is another error

```
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.digits.sdk.android.AuthClient com.digits.sdk.android.Digits.getAuthClient()' on a null object reference
                                                                   at com.digits.sdk.android.DigitsAuthButton.getAuthClient(DigitsAuthButton.java:104)
                                                                   at com.digits.sdk.android.DigitsAuthButton.onClick(DigitsAuthButton.java:73)
                                                                   at android.view.View.performClick(View.java:5669)
                                                                   at android.view.View$PerformClick.run(View.java:22539)
                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6290)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
