### ISSUE TITLE
Digits (java.lang.IndexOutOfBoundsException: setSpan (21 ... 21) ends beyond length 11)Error in lenovo

### ISSUE THREAD

**Issue by Eldho93** [crashlytics/digits-android#99]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chillarcards.campuswallet/com.digits.sdk.android.ConfirmationCodeActivity}: java.lang.IndexOutOfBoundsException: setSpan (21 ... 21) ends beyond length 11
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2572)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
Caused by java.lang.IndexOutOfBoundsException: setSpan (21 ... 21) ends beyond length 11

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
